[package]
name = "noa"
version = "0.1.0"
edition = "2024"


[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
init_sys = { path = "../../init-system/initsys/" }
noa_inst = { path = "../../noa-cli/noa-inst/" }
tokio = { version = "1.43.0", features = ["full"] }
